name: CI

on:
  push:

env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Turbo cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .turbo/cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: npm ci --no-audit --no-fund

      - run: npm run build

      - run: npm run lint

      - run: npm run size-limit
        working-directory: packages/browser

      - run: npm run test
