name: Deploy browser candidate to CDN

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'browser@*'

env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PROD_BUCKET: 'hightouch-events'

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  deploy-cdn:
    name: Deploy to CDN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT_ID }}:role/${{ secrets.AWS_PROD_S3_SYNC_ROLE }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Parse version
        id: parse_version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG##browser@}" >> $GITHUB_OUTPUT

      - name: Set version
        working-directory: packages/browser
        run: npm version ${{ steps.parse_version.outputs.VERSION }} --allow-same-version --no-commit-hooks --no-git-tag-version

      - name: Release to CDN
        working-directory: packages/browser
        env:
          PATH_VERSION: ${{ steps.parse_version.outputs.VERSION }}
        run: npm run candidate:cdn
