name: Deploy browser candidate to CDN

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - 'browser@*'

env:
  HUSKY: 0
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PROD_BUCKET: 'hightouch-events'

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  deploy-cdn:
    name: Deploy to CDN
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: get_tag_version
        env:
          TAG: ${{ github.ref_name }}
        run: echo "PATH_VERSION=${TAG##browser@}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT_ID }}:role/${{ secrets.AWS_PROD_S3_SYNC_ROLE }}
          aws-region: us-east-1

      - name: Checkout source branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Release to CDN
        env:
          PATH_VERSION: '${{ steps.get_tag_version.outputs.PATH_VERSION }}'
        run: |
          yarn run -T browser candidate:cdn
