name: Deploy to NPM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: ${{ github.event.release.tag_name || github.ref_name }}
    secrets:
      NPM_TOKEN:
        required: true
    outputs:
      version:
        description: "The NPM package version"
        value: ${{ jobs.deploy.outputs.version }}

jobs:
  deploy:
    if: ${{ startsWith(inputs.tag, inputs.name) }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.parse_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Parse version
        id: parse_version
        env:
          TAG: ${{ inputs.tag }}
        run: echo "VERSION=${TAG##${{ inputs.name }}@}" >> $GITHUB_OUTPUT

      - name: Set version
        working-directory: ${{ inputs.working-directory}}
        run: npm version ${{ steps.parse_version.outputs.VERSION }} --allow-same-version --no-commit-hooks --no-git-tag-version

      - name: Build
        working-directory: ${{ inputs.working-directory}}
        run: npx turbo run build

      - name: Publish
        working-directory: ${{ inputs.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npm publish --access=public
