name: Changeset Release Creator

# # for now, manual trigger only
# on:
#   push:
#     paths:
#       - ".changeset/**"
#       - "packages/**"
#     branches:
#       - DISABLED

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-pr:
    name: Create or Update Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install Dependencies
        run: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 HUSKY=0 yarn install --immutable

      - name: Create or Update Release PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn update-versions-and-changelogs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
